In [1]:
a = 2
b = 'akhila'
print(type(a))
print(type(b))

<class 'int'>
<class 'str'>


In [2]:
fruits = ["apple", "banana", "cherry"]
x, y, z = fruits
print(x)
print(y)
print(z) 

apple
banana
cherry


In [7]:
import random
print(random.randrange(1,10))

3


In [8]:
#identity operators is and is not - true if same object
#membership operators in and not in
#bitwise operator &, |, ^

In [10]:
myit = iter(fruits)
print(next(myit))
print(next(myit))

apple
banana


In [16]:
import functools
l = [1,2,3,4]
f = functools.reduce(lambda x, y : x+y, l)
print(f)

y = lambda x,y : x+y
print(y(2,4))

10
6


In [17]:
num1 = [1,2,3,4]
num2 = [5,6,7,8]
res = map(lambda x,y : x+y , num1, num2)

In [20]:
print(list(res))

[6, 8, 10, 12]


In [21]:
'''accumulate() in itertools, reduce in functools. accumulate gives a list of intermediate results. accumulate(seq, func())'''

'accumulate() in itertools, reduce in functools. accumulate gives a list of intermediate results. accumulate(seq, func())'

In [27]:
def outerFunction(text): 
    text = text 
    def innerFunction(): 
        print(text) 
    return innerFunction
f = outerFunction('Hey')
f()


Hey


In [28]:
def a_out(a):
    def b_in(b):
        return a+b
    return b_in

res = a_out(2)
res(4)

6

# Numpy

In [30]:
import numpy as np
list1 = [1,2,3,4]
arr = np.array(list1)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [31]:
arr = arr + 2
print(arr)

[3 4 5 6]


In [34]:
arr2 = np.array(arr, dtype='float')
print(arr2)

[3. 4. 5. 6.]


In [36]:
arr3 = arr2.astype('str')
print(arr3)

['3.0' '4.0' '5.0' '6.0']


In [37]:
arr_obj = np.array(arr, dtype='object')
print(arr_obj)

[3 4 5 6]


In [38]:
list2 = arr.tolist()
print(list2)

[3, 4, 5, 6]


In [39]:
print(arr_obj.shape)
print(arr_obj.dtype)
print(arr_obj.ndim)
print(arr_obj.size)

(4,)
object
1
4


In [41]:
list2d = [[1,2,3],[4,5,6],[7,8,9]]
arr2d = np.array(list2d, dtype = 'float')
print(arr2d[:2, :2])

[[1. 2.]
 [4. 5.]]


In [42]:
print(arr2d>3)

[[False False False]
 [ True  True  True]
 [ True  True  True]]


# pandas

In [43]:
import pandas as pd
new_series = pd.Series([1,2,3,4,5,5,6])
print(new_series)

0    1
1    2
2    3
3    4
4    5
5    5
6    6
dtype: int64


In [44]:
print(new_series.values)
print(new_series[3])

[1 2 3 4 5 5 6]
4


In [45]:
new_series = pd.Series([1,2,34,4,5,6,7], index=['a','b','c','d','e','f','g'])
print(new_series)

a     1
b     2
c    34
d     4
e     5
f     6
g     7
dtype: int64


In [47]:
new_series[['a','c']] = 0
print(new_series)

a    0
b    2
c    0
d    4
e    5
f    6
g    7
dtype: int64


In [52]:
new_series = new_series[new_series>0]*2
print(new_series)

b    16
d    32
e    40
f    48
g    56
dtype: int64


In [55]:
import pandas as pd
df = pd.DataFrame({
    'country' : ['Kazakhstan', 'Russia', 'Ukraine', 'Belarus'],
    'population' : [12.2, 43.3, 42.2, 23.4],
    'square' : [123444, 42342, 1232, 353434]
}, index = ['K', 'R', 'U', 'B'])
df

country  population  square
K  Kazakhstan        12.2  123444
R      Russia        43.3   42342
U     Ukraine        42.2    1232
B     Belarus        23.4  353434

In [54]:
df.index.name = 'Country code'
df

country  population  square
Country code                                
K             Kazakhstan        12.2  123444
R                 Russia        43.3   42342
U                Ukraine        42.2    1232
B                Belarus        23.4  353434

In [56]:
df.columns

Index(['country', 'population', 'square'], dtype='object')

In [57]:
print(type(df['country']))

<class 'pandas.core.series.Series'>


In [58]:
print(df.loc['K'])
print(df.iloc[1])

country       Kazakhstan
population          12.2
square            123444
Name: K, dtype: object
country       Russia
population      43.3
square         42342
Name: R, dtype: object


In [61]:
df.loc['K':'U', ['country']]

country
K  Kazakhstan
R      Russia
U     Ukraine

In [66]:
print(df[df['population']>20][['country', 'population']])

   country  population
R   Russia        43.3
U  Ukraine        42.2
B  Belarus        23.4


In [69]:
df2 = df.drop(['square'], axis = 'columns')
df2

country  population
K  Kazakhstan        12.2
R      Russia        43.3
U     Ukraine        42.2
B     Belarus        23.4

In [70]:
df

country  population  square
K  Kazakhstan        12.2  123444
R      Russia        43.3   42342
U     Ukraine        42.2    1232
B     Belarus        23.4  353434

In [71]:
df.to_csv('unit1.csv')